language: java
jdk:
- openjdk7
install: mvn clean package -DskipTests=true
before_deploy:
- export base_dir="git-hook" && export package_dir="$base_dir/verigreen-git-hook" && export target_dir="$base_dir/target" && mkdir -p $package_dir && cp $target_dir/dependency/*.jar $package_dir && cp $target_dir/git-hook.jar $package_dir && cp $base_dir/vg_hook.sh $package_dir && tar -zcvf $base_dir/verigreen-git-hook.tar.gz  --transform 's:.*/::g' $package_dir/*
deploy:
  provider: releases
  api_key:
    secure: TJjC5cp8EWJAsl5JBsgGd7bQkJBKSLijxV1tTYjY2HxjiDEIiftqddeHGFuNf4kQ9ZEac1V1troclrTwrDP96TbcjpMQGVdtpM9BupBf4lLUmttZH5Yl1dx++lhKYHmBb8YIyyzmSoqD3yVAL/klkpMfU+iCHP5sC968MQ/vlpCSH2ecIZIN+GYrKJitbJj1F8Hw/kWmPRlUAFUnTGZwiSsGNhYN/tkvWDoY56g8agWxjdgLXH8ZCJT2sJk6w+rSzzKN5eeRMe15DBVgehJkVZeE/j9xKCDOXlIBru+CDPOj132/vyI2mDrBOBYsPxVnkK/n622FZGn/g05gPBH8UrG2ePRjH8BTsNhxMWFj0ids4RlExZcE/1ExrJGEx5Kh6U9L/igKXMCBEDUZ79s5GCbF/NDUyikDObtppFAsw9UmZ2qSnHKrkX1pW+tsTRIgV4hkTLC2u9xht071Q7qIJABHJqSmPWqS9sicIJNzb1Qkr3uN4FZmHNAihraV4CXhKDQNS27KHSki8OQ/mLp/LWb36G6jTidNcmDAcAwBWCs+s+0r9s3ShU4TFh7alM252aNr0P4uOmA4sayV4NfPWCESy5KeYQTlZXEg7cHfy0p/6rm039GNc9Eyt47pfPULbKaIl0Np8SuJa8U/j/OpY7MSGc+roPvNL3gMrBXKcTU=
  file: 
    - verigreen-collector-webapp/target/verigreen-collector.war
    - git-hook/verigreen-git-hook.tar.gz
  skip_cleanup: true
  on:
    repo: aleitamar/verigreen
    tags: true
    branch: master
    jdk: openjdk7